"""empty message

Revision ID: 0203a9a08497
Revises: 748c27fbc478
Create Date: 2025-09-03 20:07:39.554979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0203a9a08497'
down_revision = '748c27fbc478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_ministerio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_contenido', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_ministerio', schema=None) as batch_op:
        batch_op.drop_column('tipo_contenido')

    # ### end Alembic commands ###
