"""empty message

Revision ID: 128e8de7988d
Revises: 0203a9a08497
Create Date: 2025-11-10 13:31:43.376473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128e8de7988d'
down_revision = '0203a9a08497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos',
    sa.Column('id_concepto', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre_concepto', sa.String(length=255), nullable=False),
    sa.Column('valor_base', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_concepto')
    )
    op.create_table('grados',
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre_grado', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_grado')
    )
    op.create_table('estudiantes',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('correo_responsable', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_grado'], ['grados.id_grado'], ),
    sa.PrimaryKeyConstraint('id_estudiante')
    )
    op.create_table('transacciones_recibos',
    sa.Column('id_transaccion', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_usuario_creador', sa.Integer(), nullable=False),
    sa.Column('fecha_transaccion', sa.DateTime(), nullable=False),
    sa.Column('total_recibo', sa.Float(), nullable=False),
    sa.Column('tipo_pago', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_usuario_creador'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_transaccion')
    )
    op.create_table('detalle_recibo',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_transaccion', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_concepto', sa.Integer(), nullable=False),
    sa.Column('valor_cobrado', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_concepto'], ['conceptos.id_concepto'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_transaccion'], ['transacciones_recibos.id_transaccion'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_recibo')
    op.drop_table('transacciones_recibos')
    op.drop_table('estudiantes')
    op.drop_table('grados')
    op.drop_table('conceptos')
    # ### end Alembic commands ###
