"""empty message

Revision ID: 21b2e1ad7759
Revises: 
Create Date: 2025-08-15 19:54:19.796344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b2e1ad7759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email_contacto', sa.String(length=120), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('creado_por_admin_general_id', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('tipos_respuesta',
    sa.Column('id_tipo_respuesta', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_respuesta'),
    sa.UniqueConstraint('nombre_tipo')
    )
    op.create_table('espacios',
    sa.Column('id_espacio', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre_espacio', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_espacio')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('imagen_perfil_url', sa.String(length=500), nullable=True),
    sa.Column('cambio_password_requerido', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('telefono_personal', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('favoritos', sa.JSON(), nullable=False),
    sa.Column('firma_digital_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('formularios',
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre_formulario', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('max_submissions_per_period', sa.Integer(), nullable=False),
    sa.Column('submission_period_days', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('es_plantilla', sa.Boolean(), nullable=False),
    sa.Column('es_plantilla_global', sa.Boolean(), nullable=False),
    sa.Column('compartir_con_empresas_ids', sa.JSON(), nullable=False),
    sa.Column('notificaciones_activas', sa.Boolean(), nullable=False),
    sa.Column('automatizacion_activa', sa.Boolean(), nullable=False),
    sa.Column('scheduled_automation_time', sa.Time(), nullable=True),
    sa.Column('last_automated_run_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_formulario')
    )
    op.create_table('sub_espacios',
    sa.Column('id_subespacio', sa.Integer(), nullable=False),
    sa.Column('id_espacio', sa.Integer(), nullable=False),
    sa.Column('nombre_subespacio', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_espacio'], ['espacios.id_espacio'], ),
    sa.PrimaryKeyConstraint('id_subespacio')
    )
    op.create_table('envios_formulario',
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_envio', sa.DateTime(), nullable=False),
    sa.Column('fechas_horas_actividad_reales', sa.JSON(), nullable=True),
    sa.Column('completado_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('espacios_cubiertos_ids', sa.JSON(), nullable=True),
    sa.Column('subespacios_cubiertos_ids', sa.JSON(), nullable=True),
    sa.Column('objetos_cubiertos_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_formulario'], ['formularios.id_formulario'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_envio')
    )
    op.create_table('formulario_espacio',
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('id_espacio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_espacio'], ['espacios.id_espacio'], ),
    sa.ForeignKeyConstraint(['id_formulario'], ['formularios.id_formulario'], ),
    sa.PrimaryKeyConstraint('id_formulario', 'id_espacio')
    )
    op.create_table('formulario_subespacio',
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('id_subespacio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_formulario'], ['formularios.id_formulario'], ),
    sa.ForeignKeyConstraint(['id_subespacio'], ['sub_espacios.id_subespacio'], ),
    sa.PrimaryKeyConstraint('id_formulario', 'id_subespacio')
    )
    op.create_table('formulario_tipo_respuesta',
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('id_tipo_respuesta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_formulario'], ['formularios.id_formulario'], ),
    sa.ForeignKeyConstraint(['id_tipo_respuesta'], ['tipos_respuesta.id_tipo_respuesta'], ),
    sa.PrimaryKeyConstraint('id_formulario', 'id_tipo_respuesta')
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('id_usuario_destinatario', sa.Integer(), nullable=True),
    sa.Column('tipo_notificacion', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_hora_programada', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_enviada', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('frecuencia_notificacion', sa.String(length=50), nullable=False),
    sa.Column('horas_especificas_envio', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_formulario'], ['formularios.id_formulario'], ),
    sa.ForeignKeyConstraint(['id_usuario_destinatario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('objetos',
    sa.Column('id_objeto', sa.Integer(), nullable=False),
    sa.Column('id_subespacio', sa.Integer(), nullable=False),
    sa.Column('nombre_objeto', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_subespacio'], ['sub_espacios.id_subespacio'], ),
    sa.PrimaryKeyConstraint('id_objeto')
    )
    op.create_table('preguntas',
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('texto_pregunta', sa.Text(), nullable=False),
    sa.Column('tipo_respuesta_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('opciones_respuesta_json', sa.JSON(), nullable=True),
    sa.Column('recurso_asociado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_formulario'], ['formularios.id_formulario'], ),
    sa.ForeignKeyConstraint(['tipo_respuesta_id'], ['tipos_respuesta.id_tipo_respuesta'], ),
    sa.PrimaryKeyConstraint('id_pregunta')
    )
    op.create_table('formulario_objeto',
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('id_objeto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_formulario'], ['formularios.id_formulario'], ),
    sa.ForeignKeyConstraint(['id_objeto'], ['objetos.id_objeto'], ),
    sa.PrimaryKeyConstraint('id_formulario', 'id_objeto')
    )
    op.create_table('observaciones',
    sa.Column('id_observacion', sa.Integer(), nullable=False),
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.Column('id_espacio', sa.Integer(), nullable=True),
    sa.Column('id_subespacio', sa.Integer(), nullable=True),
    sa.Column('texto_observacion', sa.Text(), nullable=False),
    sa.Column('fecha_hora_observacion', sa.DateTime(), nullable=False),
    sa.Column('resuelta', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('resuelto_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_envio'], ['envios_formulario.id_envio'], ),
    sa.ForeignKeyConstraint(['id_espacio'], ['espacios.id_espacio'], ),
    sa.ForeignKeyConstraint(['id_subespacio'], ['sub_espacios.id_subespacio'], ),
    sa.ForeignKeyConstraint(['resuelto_por_usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_observacion')
    )
    op.create_table('respuestas',
    sa.Column('id_respuesta', sa.Integer(), nullable=False),
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('valor_booleano', sa.Boolean(), nullable=True),
    sa.Column('valor_numerico', sa.Float(), nullable=True),
    sa.Column('valores_multiples_json', sa.JSON(), nullable=True),
    sa.Column('valor_firma_url', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_envio'], ['envios_formulario.id_envio'], ),
    sa.ForeignKeyConstraint(['id_pregunta'], ['preguntas.id_pregunta'], ),
    sa.PrimaryKeyConstraint('id_respuesta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas')
    op.drop_table('observaciones')
    op.drop_table('formulario_objeto')
    op.drop_table('preguntas')
    op.drop_table('objetos')
    op.drop_table('notificaciones')
    op.drop_table('formulario_tipo_respuesta')
    op.drop_table('formulario_subespacio')
    op.drop_table('formulario_espacio')
    op.drop_table('envios_formulario')
    op.drop_table('sub_espacios')
    op.drop_table('formularios')
    op.drop_table('usuarios')
    op.drop_table('espacios')
    op.drop_table('tipos_respuesta')
    op.drop_table('empresas')
    # ### end Alembic commands ###
