"""empty message

Revision ID: 25f37ebdda4b
Revises: 8cd9f585b2c1
Create Date: 2026-02-11 16:39:11.101991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f37ebdda4b'
down_revision = '8cd9f585b2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
