"""empty message

Revision ID: 42da8081ec2b
Revises: 21b2e1ad7759
Create Date: 2025-08-18 23:20:21.836997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42da8081ec2b'
down_revision = '21b2e1ad7759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_ministerio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_ministerio')
    # ### end Alembic commands ###
