"""empty message

Revision ID: 5ab8c1da1b1c
Revises: 128e8de7988d
Create Date: 2025-11-10 18:11:11.673585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab8c1da1b1c'
down_revision = '128e8de7988d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones_recibos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_pagado', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('saldo_pendiente', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones_recibos', schema=None) as batch_op:
        batch_op.drop_column('saldo_pendiente')
        batch_op.drop_column('monto_pagado')

    # ### end Alembic commands ###
