"""empty message

Revision ID: 748c27fbc478
Revises: 97b0c728949a
Create Date: 2025-08-28 13:01:29.045813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748c27fbc478'
down_revision = '97b0c728949a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formularios', schema=None) as batch_op:
        # Agregamos la columna con un valor por defecto ('0') para que no falle la migración.
        # De esta manera, todos los formularios existentes recibirán el valor 0.
        batch_op.add_column(sa.Column('automation_submissions_count', sa.Integer(), nullable=False, server_default='0'))
        
        # Después, removemos el valor por defecto para que las nuevas filas no lo tengan.
        batch_op.alter_column('automation_submissions_count', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.drop_column('automation_submissions_count')

    # ### end Alembic commands ###
