"""empty message

Revision ID: 8cd9f585b2c1
Revises: 5ab8c1da1b1c
Create Date: 2025-11-10 21:26:14.779709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd9f585b2c1'
down_revision = '5ab8c1da1b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
