"""empty message

Revision ID: 93eb615b8f52
Revises: c7594e423393
Create Date: 2025-08-19 00:42:35.072738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eb615b8f52'
down_revision = 'c7594e423393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
