"""empty message

Revision ID: 97b0c728949a
Revises: 9c533e9a10df
Create Date: 2025-08-21 20:17:52.644965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b0c728949a'
down_revision = '9c533e9a10df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
