"""empty message

Revision ID: 9c533e9a10df
Revises: 93eb615b8f52
Create Date: 2025-08-20 21:18:08.561588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c533e9a10df'
down_revision = '93eb615b8f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
